### ISSUE TITLE
program can't find protractor.conf.js

### ISSUE THREAD

**Issue by michelle-chiang** [mrsheepuk/docker-protractor#10]
When I run `docker run --rm -v web:/project mrsheepuk/protractor protractor protractor.conf.js` in the terminal, the program can't find my protractor.conf.js file, even though it's in the web folder.

```
$ docker run --rm -v /Users/michelle/Workspace/web:/project mrsheepuk/protractor protractor protractor.conf.js
[19:46:20] E/configParser - Error code: 105
[19:46:20] E/configParser - Error message: failed loading configuration file protractor.conf.js
[19:46:20] E/configParser - Error: Cannot find module '/protractor.conf.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at ConfigParser.addFileConfig (/usr/lib/node_modules/protractor/built/configParser.js:127:26)
    at Object.initFn [as init] (/usr/lib/node_modules/protractor/built/launcher.js:95:22)
    at Object.<anonymous> (/usr/lib/node_modules/protractor/built/cli.js:112:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

```

**Comment by michelle-chiang** [comment]
I fixed the end to ./project/protractor.conf.js and got the same issue described in #6.
