### ISSUE TITLE
E/launcher - unknown error: Chrome failed to start: crashed

### ISSUE THREAD

**Issue by mmraghavendra** [mrsheepuk/docker-protractor#3]
Below are the logs. how this can be solved?. For chrome browser config, seeing "E/launcher - unknown error: Chrome failed to start: crashed". See logs at the end.

$ docker run --rm -v /c/Users/Kitematic/protractor/example:/project mrsheepuk/protractor
2016-10-05 11:37:51,806 CRIT Supervisor running as root (no user in config file)
2016-10-05 11:37:51,806 INFO Included extra file "/etc/supervisor/conf.d/protractor.conf" during parsing
2016-10-05 11:37:51,807 INFO Included extra file "/etc/supervisor/conf.d/webdriver.conf" during parsing
2016-10-05 11:37:51,807 INFO Included extra file "/etc/supervisor/conf.d/xvfb.conf" during parsing
2016-10-05 11:37:51,818 INFO RPC interface 'supervisor' initialized
2016-10-05 11:37:51,819 CRIT Server 'unix_http_server' running without any HTTP
authentication checking
2016-10-05 11:37:51,819 INFO supervisord started with pid 1
2016-10-05 11:37:52,825 INFO spawned: 'webdriver' with pid 7
2016-10-05 11:37:52,832 INFO spawned: 'xvfb' with pid 8
2016-10-05 11:37:52,856 INFO spawned: 'protractor' with pid 9
Waiting for Selenium...
2016-10-05 11:37:54,637 INFO success: webdriver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-10-05 11:37:54,638 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-10-05 11:37:54,639 INFO success: protractor entered RUNNING state, process
has stayed up for > than 1 seconds (startsecs)
[11:38:03] I/launcher - Running 1 instances of WebDriver
[11:39:03] E/launcher - unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.22.397932 (282ed7cf89cf0053b6542e0d0f039d4123bbb6
ad),platform=Linux 4.4.17-boot2docker x86_64)
[11:39:03] E/launcher - WebDriverError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.22.397932 (282ed7cf89cf0053b6542e0d0f039d4123bbb6
ad),platform=Linux 4.4.17-boot2docker x86_64)
    at WebDriverError (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:10)
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:538:13)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:472:11
    at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (node.js:364:9)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Driver (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:778:38)
    at Direct.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/direct.js:68:26)
    at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:190:43)
    at /usr/local/lib/node_modules/protractor/built/runner.js:264:30
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:83
4:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:137
:13)
[11:39:03] E/launcher - Process exited with error code 199
2016-10-05 11:39:03,460 INFO reaped unknown pid 41
2016-10-05 11:39:03,576 INFO waiting for webdriver, xvfb, protractor to die
2016-10-05 11:39:03,576 INFO stopped: protractor (terminated by SIGTERM)
2016-10-05 11:39:03,579 INFO stopped: xvfb (exit status 0)
2016-10-05 11:39:03,582 INFO stopped: webdriver (terminated by SIGTERM)

mmraghavendra@lptw-mmraghavendra MINGW64 /d/office/docker/test
$
# 

For chrome browser, seeing below error
[11:39:03] E/launcher - unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.22.397932 (282ed7cf89cf0053b6542e0d0f039d4123bbb6
ad),platform=Linux 4.4.17-boot2docker x86_64)
[11:39:03] E/launcher - WebDriverError: unknown error: Chrome failed to start: c
rashed
  (Driver info: chromedriver=2.22.397932 (282ed7cf89cf0053b6542e0d0f039d4123bbb6
ad),platform=Linux 4.4.17-boot2docker x86_64)
    at WebDriverError (/usr/local/lib/node_modules/protractor/node_modules/selen
ium-webdriver/lib/error.js:27:10)
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_m
odules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/se
lenium-webdriver/http/index.js:538:13)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/ht
tp/index.js:472:11
    at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/no
de_modules/selenium-webdriver/lib/promise.js:1379:14)

**Comment by mrsheepuk** [comment]
Regarding Firefox, that is not installed in this Dockerfile so I would not expect it to work. Only the Chromium browser is installed.

Regarding the Chrome crash issue, can you share the protractor config file you are using? The following is the one I've used successfully in the past:

```
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  framework: "jasmine2",
  onPrepare: function () {
    var JUnitXmlReporter = require('jasmine-reporters').JUnitXmlReporter;
    jasmine.getEnv().addReporter(new JUnitXmlReporter({
      savePath: 'target',
      consolidateAll: false
    }));
  },
  specs: ['*.spec.js'],
  // Chrome is not allowed to create a SUID sandbox when running inside Docker  
  capabilities: {
    'browserName': 'chrome',
    'chromeOptions': {
      'args': ['no-sandbox']
    }
  }
};
```

**Comment by mrsheepuk** [comment]
I've just noticed it does suggest in the README that firefox is installed; sorry about that, that's not correct and I'll update it to clarify.

I've just tested the latest version of this image with my test project and it runs correctly against Chrome for me.

**Comment by mmraghavendra** [comment]
Thank you.. its working now with chrome after setting chrome options. Do you have plans to add firefox support soon?.

**Comment by mrsheepuk** [comment]
I've added something to the readme to show the required chrome option;
thanks for reporting the issue.

I'll take a look at Firefox support if i get chance, it may be as simple as
adding it to the apt-get install line in the Dockerfile.

**Comment by mrsheepuk** [comment]
Created new issue for firefox, closing this issue now as the main problem referenced in this issue was addressed with the doc update.
